# NumPy array excursions

The purpose of this notebook is to explore multidimensional NumPy arrays so that DECSKS can manipulate higher order objects instead of passing only 1D arrays in the application of convected scheme (DECSKS.lib.convect.scheme). We aim to better understand the array structures by some index slicing exercises as well as verifying products of higher order objects reproduce the same computations as the 1D array multiplications that are involved in convected scheme.

The 1D1V version of DECSKS evolves a density function $f = f(t,x,v)\in \mathbb{R}^+\times\mathbb{R}\times\mathbb{R}$, stored as a three-dimensional array $\underline{\underline{f}} = \underline{\underline{f}}(\underline{t},\underline{x},\underline{v})\in [0,T]\times\mathcal{D}_x\times\mathcal{D}_v$

where

\begin{eqnarray*}
\underline{t} & = (t^n) = & (t^0, t^1, t^2, \ldots , t^{N_t})\\
&& \\
\underline{x} & = (x_i) = & (x_0, x_1, x_2, \ldots , x_{N_x - 1}) \\
&& \\
\underline{v} & = (v_j) = & (v_0, v_1, v_2, \ldots , v_{N_v - 1}) 
\end{eqnarray*}

We define spacings on the uniform grids as:

$$\Delta t = \frac{T}{N_t}, \qquad \Delta x = \frac{L_x}{N_x - 1}, \qquad \Delta v = \frac{L_v}{N_v - 1}$$

$T\in\mathbb{R}^+$ is the simulation time, $L_x = |\mathcal{D}_x| = |b_x - a_x|$ and $L_v = |\mathcal{D}_v| = b_v - a_v$, so that

$$t^n = n\Delta t, \qquad x_i = a_x + i\Delta x, \qquad v_j = a_v + j\Delta v$$

for $\mathcal{D}_x = [a_x,b_x]$, $\mathcal{D}_v = [a_v,b_v]$, $a_x,a_v,b_x,b_v\in\mathbb{R}$ consistute the $x$ and $v$ grids. In this notebook, we are only interested in understanding the shapes of higher dimensional arrays and how to index them in a way that allows confident access of anything desired. Hence, the contents of the array does not matter inasmuch as the elements of each vector can be traced. We create numpy arrays of strings for easy identification and decide on distinct sizes: $N_x = 5, N_v = 7, N_t = 3$ since it is a rare case that we elect to use the same number of gridpoints in more than one grid. Each vector $\underline{x}, \underline{v}, \underline{t}$ are themselves 1D which altogether constitute a 3D object by straightforward cartesian product. Note, that $N_t$ is the number of timesteps, not the number of time gridpoints, hence we have $N_t+1$ time gridpoints, whereas all other phase space variables we use the definition that $N_{x,v}$ denotes the total number of gridpoints, hence we have the following vectors enumerated per 0-based indexing

    x = ['x0', 'x1', 'x2', 'x3', 'x4']
    v = ['v0', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6']
    t = ['t0', 't1', 't2', 't3']
    
Construct the arrays:

In [75]:
import numpy as np

x = np.array(['x0', 'x1', 'x2', 'x3', 'x4'])
v = np.array(['v0', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6'])
t = np.array(['t0', 't1', 't2', 't3'])

Nx,Nv = len(x), len(v)
Nt = len(t) - 1

create a higher order object f = f(t,x,v). In a 1D1V Vlasovian electrostatic plasma, f is density function whose value at each (x,v) gives the density at some time t. Here, layering more physical significant gets in the way of our goal of our indexing exercise. Hence, for clarity we choose f to be the identity function, so that f = f(t,x,v) = (t,x,v) is the 3D object itself. We load densities in a straightforward way, casting each entry as a 3-tuple.

In [76]:
f = np.chararray([Nt+1,Nx,Nv], itemsize = 14)
comma = ','
delimiter_left = '('
delimiter_right = ')'

for n in range(Nt+1):
    for i in range(Nx):
        for j in range(Nv):
            entry = delimiter_left + t[n] + comma + x[i] + comma + v[j] + delimiter_right
            f[n,i,j] = entry

we now do some index slicing to see what kinds of arrays we get. If I try f(t0,x,v) on paper, I would expect to get a 2D array with ordered pairs (x,v) for time zero t0.

In [77]:
print f[0,:,:]

[['(t0,x0,v0)' '(t0,x0,v1)' '(t0,x0,v2)' '(t0,x0,v3)' '(t0,x0,v4)'
  '(t0,x0,v5)' '(t0,x0,v6)']
 ['(t0,x1,v0)' '(t0,x1,v1)' '(t0,x1,v2)' '(t0,x1,v3)' '(t0,x1,v4)'
  '(t0,x1,v5)' '(t0,x1,v6)']
 ['(t0,x2,v0)' '(t0,x2,v1)' '(t0,x2,v2)' '(t0,x2,v3)' '(t0,x2,v4)'
  '(t0,x2,v5)' '(t0,x2,v6)']
 ['(t0,x3,v0)' '(t0,x3,v1)' '(t0,x3,v2)' '(t0,x3,v3)' '(t0,x3,v4)'
  '(t0,x3,v5)' '(t0,x3,v6)']
 ['(t0,x4,v0)' '(t0,x4,v1)' '(t0,x4,v2)' '(t0,x4,v3)' '(t0,x4,v4)'
  '(t0,x4,v5)' '(t0,x4,v6)']]


This checks out. If I try f(0,x,v1), I would expect to get a 1D array of all x values with velocity v1, at time 0.

In [78]:
print f[0,:,1]

['(t0,x0,v1)' '(t0,x1,v1)' '(t0,x2,v1)' '(t0,x3,v1)' '(t0,x4,v1)']


This also checks out. If I try f(t3,x4,v) I would expect to get a 1D array of all v at location x4 at time t3

In [79]:
print f[3,4,:]

['(t3,x4,v0)' '(t3,x4,v1)' '(t3,x4,v2)' '(t3,x4,v3)' '(t3,x4,v4)'
 '(t3,x4,v5)' '(t3,x4,v6)']


This also checks out. Everything works as expected incidentally. If I try f(t,x2,v6), I expect to get a 1D array of all times correspondent to the pair (x2,v6). This sounds a little silly in this language, in an actual problem this would correspond to the density at (x2,v6) over all times in the simulation.

In [80]:
print f[:,2,6]

['(t0,x2,v6)' '(t1,x2,v6)' '(t2,x2,v6)' '(t3,x2,v6)']


In [83]:
print x
print v
print t

['x0' 'x1' 'x2' 'x3' 'x4']
['v0' 'v1' 'v2' 'v3' 'v4' 'v5' 'v6']
['t0' 't1' 't2' 't3']


Next, we try to recast 1D array multiplications with CFL numbers at a given x or v, and try to do it in one sweep as array (matrix) multiplication.

To examine how array multiplication transpires, we require numerical entries. We set up

\begin{eqnarray*}
\underline{x} & = & (x_0, x_1, x_2, x_3, x_4) = (10, 11, 12, 13, 14) \\
&& \\
\underline{v} & = & (v_0, v_1, v_2, v_3, v_4, v_5, v_6) = (20, 21, 22, 23, 24, 25, 26) \\
&& \\
\underline{t} & = & (t_0, t_1, t_2, t_3) = (0, 1, 2, 3)
\end{eqnarray*}

And construct the array f as

$$\underline{\underline{f}} = \left\{
\left(\begin{array}{ccc ccc c} 
x_0v_0 & x_0v_1 & x_0v_2 & x_0v_3 & x_0v_4 & x_0v_5 &x_0v_6 \\
x_1v_0 & x_1v_1 & x_1v_2 & x_1v_3 & x_1v_4 & x_1v_5 &x_1v_6 \\
x_2v_0 & x_2v_1 & x_2v_2 & x_2v_3 & x_2v_4 & x_2v_5 &x_2v_6 \\
x_3v_0 & x_3v_1 & x_3v_2 & x_3v_3 & x_3v_4 & x_3v_5 &x_3v_6 \\
x_4v_0 & x_4v_1 & x_4v_2 & x_4v_3 & x_4v_4 & x_4v_5 &x_4v_6 
\end{array}
\right)_{t = t_0}\\
\left(\begin{array}{ccc ccc c} 
x_0v_0 & x_0v_1 & x_0v_2 & x_0v_3 & x_0v_4 & x_0v_5 &x_0v_6 \\
x_1v_0 & x_1v_1 & x_1v_2 & x_1v_3 & x_1v_4 & x_1v_5 &x_1v_6 \\
x_2v_0 & x_2v_1 & x_2v_2 & x_2v_3 & x_2v_4 & x_2v_5 &x_2v_6 \\
x_3v_0 & x_3v_1 & x_3v_2 & x_3v_3 & x_3v_4 & x_3v_5 &x_3v_6 \\
x_4v_0 & x_4v_1 & x_4v_2 & x_4v_3 & x_4v_4 & x_4v_5 &x_4v_6 
\end{array}
\right)_{t = t_1}\\
\left(\begin{array}{ccc ccc c} 
x_0v_0 & x_0v_1 & x_0v_2 & x_0v_3 & x_0v_4 & x_0v_5 &x_0v_6 \\
x_1v_0 & x_1v_1 & x_1v_2 & x_1v_3 & x_1v_4 & x_1v_5 &x_1v_6 \\
x_2v_0 & x_2v_1 & x_2v_2 & x_2v_3 & x_2v_4 & x_2v_5 &x_2v_6 \\
x_3v_0 & x_3v_1 & x_3v_2 & x_3v_3 & x_3v_4 & x_3v_5 &x_3v_6 \\
x_4v_0 & x_4v_1 & x_4v_2 & x_4v_3 & x_4v_4 & x_4v_5 &x_4v_6 
\end{array}
\right)_{t = t_2} \\
\left(\begin{array}{ccc ccc c} 
x_0v_0 & x_0v_1 & x_0v_2 & x_0v_3 & x_0v_4 & x_0v_5 &x_0v_6 \\
x_1v_0 & x_1v_1 & x_1v_2 & x_1v_3 & x_1v_4 & x_1v_5 &x_1v_6 \\
x_2v_0 & x_2v_1 & x_2v_2 & x_2v_3 & x_2v_4 & x_2v_5 &x_2v_6 \\
x_3v_0 & x_3v_1 & x_3v_2 & x_3v_3 & x_3v_4 & x_3v_5 &x_3v_6 \\
x_4v_0 & x_4v_1 & x_4v_2 & x_4v_3 & x_4v_4 & x_4v_5 &x_4v_6 
\end{array}
\right)_{t = t_3}
\right\}$$

Here, $t$ fulfills the third dimension. To help with our intuition, we can regard $t$ as enumerating "pages" of 2D arrays $x_iv_j = x_i(t)v_j(t)$. In DECSKS, we begin with a container f = np.zeros([t.Ngridpoints, x.N, v.N]), and intialize the problem by filling the density at time zero f[0, :, :] $\equiv \underline{\underline{f}}(0,\underline{x},\underline{v})$. Time stepping must one-by-one fill in the remaining entries f[1:, :, :] $\equiv \underline{\underline{f}}(\underline{t} > 0, \underline{x},\underline{v})$. Thus, the multiplications we are interested in involve 2D arrays. We pick any $t$ above, and thus examine matrices that look like

$$\underline{\underline{g}} = \left(\begin{array}{ccc ccc c} 
x_0v_0 & x_0v_1 & x_0v_2 & x_0v_3 & x_0v_4 & x_0v_5 &x_0v_6 \\
x_1v_0 & x_1v_1 & x_1v_2 & x_1v_3 & x_1v_4 & x_1v_5 &x_1v_6 \\
x_2v_0 & x_2v_1 & x_2v_2 & x_2v_3 & x_2v_4 & x_2v_5 &x_2v_6 \\
x_3v_0 & x_3v_1 & x_3v_2 & x_3v_3 & x_3v_4 & x_3v_5 &x_3v_6 \\
x_4v_0 & x_4v_1 & x_4v_2 & x_4v_3 & x_4v_4 & x_4v_5 &x_4v_6 
\end{array}
\right)$$

Which we decide is an object that has been computed as the dyadic $\underline{x}\underline{v}$ just so we can keep track easily of the multiplication that transpires. We construct the array g below:

In [92]:
import numpy as np

x = np.array([10, 11, 12, 13, 14])
v = np.array([20, 21, 22, 23, 24, 25, 26])

g = np.outer(x,v)

We check the entries have been computed properly in the following loop:

In [104]:
for i in range(len(x)):
    for j in range(len(v)):
        entry = x[i]*v[j]
        
        if g[i,j] == entry:
            print "TRUE: g[%d,%d] = x[%d]v[%d] = %d*%d = %d" % (i,j, i,j, x[i], v[j], entry)
        else:
            print "FALSE: the entry is not the expected product"

TRUE: g[0,0] = x[0]v[0] = 10*20 = 200
TRUE: g[0,1] = x[0]v[1] = 10*21 = 210
TRUE: g[0,2] = x[0]v[2] = 10*22 = 220
TRUE: g[0,3] = x[0]v[3] = 10*23 = 230
TRUE: g[0,4] = x[0]v[4] = 10*24 = 240
TRUE: g[0,5] = x[0]v[5] = 10*25 = 250
TRUE: g[0,6] = x[0]v[6] = 10*26 = 260
TRUE: g[1,0] = x[1]v[0] = 11*20 = 220
TRUE: g[1,1] = x[1]v[1] = 11*21 = 231
TRUE: g[1,2] = x[1]v[2] = 11*22 = 242
TRUE: g[1,3] = x[1]v[3] = 11*23 = 253
TRUE: g[1,4] = x[1]v[4] = 11*24 = 264
TRUE: g[1,5] = x[1]v[5] = 11*25 = 275
TRUE: g[1,6] = x[1]v[6] = 11*26 = 286
TRUE: g[2,0] = x[2]v[0] = 12*20 = 240
TRUE: g[2,1] = x[2]v[1] = 12*21 = 252
TRUE: g[2,2] = x[2]v[2] = 12*22 = 264
TRUE: g[2,3] = x[2]v[3] = 12*23 = 276
TRUE: g[2,4] = x[2]v[4] = 12*24 = 288
TRUE: g[2,5] = x[2]v[5] = 12*25 = 300
TRUE: g[2,6] = x[2]v[6] = 12*26 = 312
TRUE: g[3,0] = x[3]v[0] = 13*20 = 260
TRUE: g[3,1] = x[3]v[1] = 13*21 = 273
TRUE: g[3,2] = x[3]v[2] = 13*22 = 286
TRUE: g[3,3] = x[3]v[3] = 13*23 = 299
TRUE: g[3,4] = x[3]v[4] = 13*24 = 312
TRUE: g[3,5]

Thus, we have the following array to work with

In [103]:
print 'g = '
print g

print '\n which has dimensions %s' % (str(g.shape))

g = 
[[200 210 220 230 240 250 260]
 [220 231 242 253 264 275 286]
 [240 252 264 276 288 300 312]
 [260 273 286 299 312 325 338]
 [280 294 308 322 336 350 364]]

 which has dimensions (5, 7)


Currently, DECSKS updates every 1D subarray in routines that look like (note, the phase space variables x and v and time variable t are instantiations of class objects that carry with them attriutes that fully characterize them, number of gridpoints, prepoint values, postpoints of all the MCs, domain boundaries, etc. The attribute names below should be clear enough to follow the meaning in the below pseudo-code) :

    if convecting in x:
        for j in v.prepoints:
            x.MCs   = x.generate_Lagrangian_mesh(x.prepointvalues, v.prepointvalues[j], frac*t.width)
            g[:,j] = DECSKS.lib.convect.scheme(g[:,j], sim_params, args*)
    
    elif convecting in v:
        compute acceleration a = a(x)
        for i in x.indices:
            v.MCs   = v.generate_Lagrangian_mesh(v.prepointvalues, a[i], frac*t.width)
            g[i,:] = DECSKS.lib.convect.scheme(g[i,:], sim_params, args*)
        
where a is a self-consistently computed acceleration. We wish to recast the above in terms of something to the effect of:

    if convecting in x:
        x.MCs   = x.generate_Lagrangian_mesh(x.prepointvalues, v.prepointvalues, frac*t.width)
        g = DECSKS.lib.convect.scheme(g, sim_params, args*)
    elif convecting in v
        compute acceleration a = a(x)
        v.MCs   = v.generate_Lagrangian_mesh(v.prepointvalues, frac*t.width)
        g = DECSKS.lib.convect.scheme(g, sim_params, args*)
    
where 2D arrays are passed. and x.MCs and v.MCs should be recasted from 1D arrays to a collection of 1D arrays (i.e. 2D array) that can calculate and store all the MC postpoints for all prepoints in x and v by passing, say instead of v.prepointvalues[j], we pass v.prepointvalues as a whole).

In [115]:
print x
print v

[10 11 12 13 14]
[20 21 22 23 24 25 26]


In [133]:

one = np.ones(len(v))
X = np.outer(x,one)

X + v*.01

array([[ 10.2 ,  10.21,  10.22,  10.23,  10.24,  10.25,  10.26],
       [ 11.2 ,  11.21,  11.22,  11.23,  11.24,  11.25,  11.26],
       [ 12.2 ,  12.21,  12.22,  12.23,  12.24,  12.25,  12.26],
       [ 13.2 ,  13.21,  13.22,  13.23,  13.24,  13.25,  13.26],
       [ 14.2 ,  14.21,  14.22,  14.23,  14.24,  14.25,  14.26]])

In [172]:
onet = np.ones([1,len(v)])

In [173]:
onet.shape

(1, 7)

In [175]:
onet[0,1]

1.0

In [176]:
onett = np.ones([1,len(x)])

In [190]:
np.outer(x,np.ones([1,len(v)])) + np.outer(np.ones([len(x),1]),v*.01)

array([[ 10.2 ,  10.21,  10.22,  10.23,  10.24,  10.25,  10.26],
       [ 11.2 ,  11.21,  11.22,  11.23,  11.24,  11.25,  11.26],
       [ 12.2 ,  12.21,  12.22,  12.23,  12.24,  12.25,  12.26],
       [ 13.2 ,  13.21,  13.22,  13.23,  13.24,  13.25,  13.26],
       [ 14.2 ,  14.21,  14.22,  14.23,  14.24,  14.25,  14.26]])

In [188]:
print np.transpose(x).shape
print x.shape

(5,)
(5,)


In [194]:
z = np.zeros([1,5])
print z.shape
print np.transpose(z).shape

(1, 5)
(5, 1)


In [198]:
lst = ['a', 'c', 'd']

if 'b' in lst:
    print 'yes'
else:
    print 'no'

no


In [253]:
import numpy as np
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])

In [235]:
 mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
    


In [242]:
ind = index([mx.mask == True])

NameError: name 'index' is not defined

In [205]:
x.mean()

2.0

In [206]:
(1 + 2 + 3 + 5) / 4.

2.75

In [207]:
(1 + 2 + 3 - 1 + 5) / 5.

2.0

In [208]:
len(mx)

5

In [209]:
len(x)

5

In [210]:
print mx

[1 2 3 -- 5]


In [211]:
sum(mx)

masked

In [213]:
mx

masked_array(data = [1 2 3 -- 5],
             mask = [False False False  True False],
       fill_value = 999999)

In [214]:
mx.data

array([ 1,  2,  3, -1,  5])

In [220]:
mx.data[3]

-1

In [221]:
x

array([ 1,  2,  3, -1,  5])

In [223]:
xmask = ma.masked_greater(x,0)

In [224]:
xmask

masked_array(data = [-- -- -- -1 --],
             mask = [ True  True  True False  True],
       fill_value = 999999)

In [225]:
xmask.data

array([ 1,  2,  3, -1,  5])

In [226]:
np.floor(2.5)

2.0

In [231]:
np.ceil(ma.masked_greater_equal(x,0))

masked_array(data = [-- -- -- -1.0 --],
             mask = [ True  True  True False  True],
       fill_value = 1e+20)

In [233]:
b = np.floor(ma.masked_less(x,0))

In [234]:
b.astype(int)

masked_array(data = [1 2 3 -- 5],
             mask = [False False False  True False],
       fill_value = 999999)

In [247]:
indexes = [i for i,x in enumerate(mx.mask) if x == False]

In [248]:
print indexes

[0, 1, 2, 4]


In [246]:
mx

masked_array(data = [1 2 3 -- 5],
             mask = [False False False  True False],
       fill_value = 999999)

In [249]:
a

array([5, 6, 7, 8])

In [251]:
a[a<6]

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [252]:
x

False

In [254]:
x

array([ 1,  2,  3, -1,  5])

In [255]:
y = np.array([1.2, 2.6, 3.1, -1,7, 5])

In [256]:
y

array([ 1.2,  2.6,  3.1, -1. ,  7. ,  5. ])

In [257]:
nonnegative_y = np.ceil(y[y>=0])

In [258]:
nonnegative_y

array([ 2.,  3.,  4.,  7.,  5.])

In [260]:
np.where(y > 3)

(array([2, 4, 5]),)

In [261]:
y[2]

3.1000000000000001

In [262]:
y[4]

7.0

In [263]:
y[5]

5.0

In [264]:
b

masked_array(data = [1.0 2.0 3.0 -- 5.0],
             mask = [False False False  True False],
       fill_value = 1e+20)

In [265]:
y

array([ 1.2,  2.6,  3.1, -1. ,  7. ,  5. ])

In [268]:
z = y.reshape(2,3)

In [269]:
y

array([ 1.2,  2.6,  3.1, -1. ,  7. ,  5. ])

In [270]:
np.where(z>3)

(array([0, 1, 1]), array([2, 1, 2]))

In [271]:
z

array([[ 1.2,  2.6,  3.1],
       [-1. ,  7. ,  5. ]])

In [272]:
z

array([[ 1.2,  2.6,  3.1],
       [-1. ,  7. ,  5. ]])

In [280]:
CFL = np.where(z>=0, np.floor(z), np.ceil(z))

In [277]:
CFL

array([[ 1.,  2.,  3.],
       [-1.,  7.,  5.]])

In [278]:
z[0,0] = 0

In [281]:
z

array([[ 0. ,  2.6,  3.1],
       [-1. ,  7. ,  5. ]])

In [282]:
np.where(z>0)

(array([0, 0, 1, 1]), array([1, 2, 1, 2]))

In [1]:
import numpy as np

class anything:
    def __init__(self, N, a = 0., b = 1.):

        self.N = N
        self.a = 0.
        self.b = 1.
        self.L = self.b - self.a
        

In [20]:
%%timeit

z = anything(N = 1028)

xi = np.zeros(z.N)
for r in range(z.N):
    if r <= z.N/2 :
        xi[r] = 2*np.pi*r / z.L
    else:
        xi[r] = 2*np.pi*(r - z.N) / z.L

1000 loops, best of 3: 443 µs per loop


In [21]:
print xi.shape

(1028,)


In [17]:
%%timeit

z = anything(N = 1028)

wave_index = np.arange(z.N)

xi = np.where(wave_index <= z.N / 2, 2*np.pi*wave_index / z.L, 2*np.pi*(wave_index - z.N) / z.L)


10000 loops, best of 3: 53.7 µs per loop


In [19]:
print xi.shape

(1028,)


### numpy.sum vs. numpy.dot

In [1]:
import numpy as np

c = np.arange(21)
d = .25

one = np.ones_like(c)

In [9]:
%%timeit
c.dot(d*one)

The slowest run took 20.45 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 5.22 µs per loop


In [11]:
%%timeit

sum = 0
for q in range(21):
    sum += c[q]*d

10000 loops, best of 3: 96.9 µs per loop


<b>numpy.dot is significantly faster than python looping</b>

## numpy.inner 

In [3]:
import numpy as np

N = 3
Nv = 5
Nx = 4

c = np.arange(N*Nv).reshape(N,Nv)
d = np.arange(20,N*Nv*Nx+20).reshape(N,Nx,Nv)

In [4]:
print "c = "
print c
print "d = "
print d

c = 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
d = 
[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]]


In [5]:
20*0 + 40*5 + 60*10 # 0,0

800

In [6]:
25*0 + 45*5 + 65*10 # 1,0

875

In [7]:
30*0 + 50*5 + 70*10 # 2,0

950

In [8]:
35*0 + 55*5 + 75*10 # 3,0

1025

In [9]:
21*1 + 41*6 + 61*11 # 0,1

938

In [19]:
import numpy as np

cd = np.zeros([Nx,Nv])
for i in range(Nx):
    for j in range(Nv):
            cd[i,j] = c[:,j].dot(d[:,i,j])
            
print cd

[[  800.   938.  1082.  1232.  1388.]
 [  875.  1028.  1187.  1352.  1523.]
 [  950.  1118.  1292.  1472.  1658.]
 [ 1025.  1208.  1397.  1592.  1793.]]


In [28]:
import numpy as np

cd = np.zeros([Nx,Nv])

for j in range(Nv):
     cd[:,j] = c[:,j].dot(d[:,:,j])
    
print cd
    

[[  800.   938.  1082.  1232.  1388.]
 [  875.  1028.  1187.  1352.  1523.]
 [  950.  1118.  1292.  1472.  1658.]
 [ 1025.  1208.  1397.  1592.  1793.]]


In [17]:
cd

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
c.shape, d.shape

((3, 5), (3, 4, 5))

In [12]:
CD = np.zeros([Nx,Nv])
for j in range(Nv):
    CD[:,j] = c[:,j].dot(d[:,:,j])

In [14]:
print CD

[[  800.   938.  1082.  1232.  1388.]
 [  875.  1028.  1187.  1352.  1523.]
 [  950.  1118.  1292.  1472.  1658.]
 [ 1025.  1208.  1397.  1592.  1793.]]


In [101]:
cd = np.tensordot(c[:,0], d[:,:,0], axes=(0,0))

In [98]:
cdotd = c[:,0].dot(d[:,0,0])

In [99]:
print cdotd

800


In [102]:
print cd

[ 800  875  950 1025]


In [97]:
print cd.shape

(5, 4, 5)


In [42]:
A = np.array(['a', 'b', 'c','d','e','f','g','h','i'], dtype = object).reshape(3,3)

In [52]:
B = np.arange(1,2+1)

In [53]:
print A

[[a b c]
 [d e f]
 [g h i]]


In [54]:
print B

[1 2]


In [56]:
AB = np.tensordot(A,B, axes = 0)

In [59]:
print AB.shape, A.shape, B.shape

(3, 3, 2) (3, 3) (2,)


In [58]:
print AB

[[[a aa]
  [b bb]
  [c cc]]

 [[d dd]
  [e ee]
  [f ff]]

 [[g gg]
  [h hh]
  [i ii]]]


In [61]:
AB[0,:,0]

array([a, b, c], dtype=object)

In [63]:
BA = np.tensordot(B,A, axes = 0)

In [69]:
print BA[0,:,0]

[a d g]


In [70]:
print BA

[[[a b c]
  [d e f]
  [g h i]]

 [[aa bb cc]
  [dd ee ff]
  [gg hh ii]]]


In [71]:
B[0]*A[:,0]

array([a, d, g], dtype=object)

In [72]:
B[0]*A[:,1]

array([b, e, h], dtype=object)

In [74]:
BA[0,:,1]

array([b, e, h], dtype=object)

In [73]:
B[0]*A[:,2]

array([c, f, i], dtype=object)

In [37]:
import numpy as np

CFL = np.random.randn(25).reshape(5,5)

In [38]:
print CFL

[[-0.42273195  0.08891318 -0.30134986 -0.41019624  0.21007889]
 [-0.68022488  0.64590769  0.30939136  0.94322453 -0.72466147]
 [ 0.87766269 -1.46644229  0.50089301  0.22964166  0.66403735]
 [ 0.87328908 -0.85639999  0.1983523  -0.32506426 -0.36472375]
 [-0.9361809   0.12797658 -0.10994567 -0.39484037  1.1583446 ]]


In [39]:
Uf = np.random.randn(25).reshape(5,5)

In [40]:
print Uf

[[ -7.80461384e-01   1.66234401e+00  -3.68889394e-01   1.11225412e+00
    1.99723283e+00]
 [ -1.06112143e+00   6.65008837e-01  -1.97112276e+00  -3.53902514e-01
   -8.32016177e-01]
 [ -1.46869364e+00   4.93447453e-03   1.29943872e-01  -2.61632608e-03
    4.21683269e-01]
 [  1.03496295e+00   1.45094291e+00   1.35367699e+00  -1.08954711e+00
    1.09502970e+00]
 [ -1.12935808e+00   3.36539040e+00   8.16306135e-01  -1.23718620e+00
    1.26039257e-01]]


In [41]:
Uf_limited = np.zeros_like(CFL)

for j in range(5):
    for i in range(5):
        if CFL[i,j] >= 0:
            Uf_limited[i,j] = min( [ max([0,Uf[i,j]]), 1.0*CFL[i,j]] )
        else: # U < 0
            Uf_limited[i,j] = min( [ max([-1.0*CFL[i,j], Uf[i,j]]), 0 ] )

In [42]:
print Uf

[[ -7.80461384e-01   1.66234401e+00  -3.68889394e-01   1.11225412e+00
    1.99723283e+00]
 [ -1.06112143e+00   6.65008837e-01  -1.97112276e+00  -3.53902514e-01
   -8.32016177e-01]
 [ -1.46869364e+00   4.93447453e-03   1.29943872e-01  -2.61632608e-03
    4.21683269e-01]
 [  1.03496295e+00   1.45094291e+00   1.35367699e+00  -1.08954711e+00
    1.09502970e+00]
 [ -1.12935808e+00   3.36539040e+00   8.16306135e-01  -1.23718620e+00
    1.26039257e-01]]


In [43]:
print CFL

[[-0.42273195  0.08891318 -0.30134986 -0.41019624  0.21007889]
 [-0.68022488  0.64590769  0.30939136  0.94322453 -0.72466147]
 [ 0.87766269 -1.46644229  0.50089301  0.22964166  0.66403735]
 [ 0.87328908 -0.85639999  0.1983523  -0.32506426 -0.36472375]
 [-0.9361809   0.12797658 -0.10994567 -0.39484037  1.1583446 ]]


In [44]:
print Uf_limited

[[ 0.          0.08891318  0.          0.          0.21007889]
 [ 0.          0.64590769  0.          0.          0.        ]
 [ 0.          0.          0.12994387  0.          0.42168327]
 [ 0.87328908  0.          0.1983523   0.          0.        ]
 [ 0.          0.12797658  0.          0.          0.12603926]]


In [89]:
import numpy.ma as ma

CFL_masked = ma.array(CFL)
CFL_masked[CFL_masked < 0] = ma.masked
zeros = ma.zeros(CFL_masked.shape)
zeros.mask = CFL_masked.mask

print "CFL_mask is"
print CFL_masked

# operating only on positive values
CFL_final_pos = ma.minimum(ma.maximum(zeros, Uf), 1.0*CFL)

print "CFL_final_pos is"
print CFL_final_pos

# mask positives, keep negatives
CFL_masked.mask = np.logical_not(CFL_masked.mask)
zeros.mask = CFL_masked.mask

print "CFL_mask after np.logical_not is"
print CFL_mask

#operating only on negative values
CFL_final_neg = ma.minimum(ma.maximum(-1.0*CFL_masked, Uf), zeros)

CFL_final = np.zeros_like(CFL)

print "CFL_final_neg is"
print CFL_final_neg

CFL_final = np.where(CFL_final_neg.mask == False, CFL_final_neg.data, CFL_final_pos.data)

print "the final CFL_final is"
print CFL_final

CFL_mask is
[[-- 0.0889131846012 -- -- 0.210078892558]
 [-- 0.645907694118 0.309391359321 0.943224534033 --]
 [0.877662688142 -- 0.500893007928 0.229641660646 0.664037347706]
 [0.873289079256 -- 0.198352304475 -- --]
 [-- 0.127976581058 -- -- 1.1583446001]]
CFL_final_pos is
[[-- 0.0889131846012 -- -- 0.210078892558]
 [-- 0.645907694118 0.0 0.0 --]
 [0.0 -- 0.129943872251 0.0 0.421683269459]
 [0.873289079256 -- 0.198352304475 -- --]
 [-- 0.127976581058 -- -- 0.1260392567]]
CFL_mask after np.logical_not is
[[-- 0.0889131846012 -- -- 0.210078892558]
 [-- 0.645907694118 0.309391359321 0.943224534033 --]
 [0.877662688142 -- 0.500893007928 0.229641660646 0.664037347706]
 [0.873289079256 -- 0.198352304475 -- --]
 [-- 0.127976581058 -- -- 1.1583446001]]
CFL_final_neg is
[[0.0 -- 0.0 0.0 --]
 [0.0 -- -- -- 0.0]
 [-- 0.0 -- -- --]
 [-- 0.0 -- 0.0 0.0]
 [0.0 -- 0.0 0.0 --]]
the final CFL_final is
[[ 0.          0.08891318  0.          0.          0.21007889]
 [ 0.          0.64590769  0.         

In [3]:
import numpy as np
CFL = np.random.randn(768,1536)
Uf = np.random.randn(768,1536)

In [4]:
%%timeit
import numpy.ma as ma
import numpy as np

CFL_masked = ma.array(CFL)
CFL_masked[CFL_masked < 0] = ma.masked
zeros = ma.zeros(CFL_masked.shape)
zeros.mask = CFL_masked.mask

# operating only on positive values
CFL_final_pos = ma.minimum(ma.maximum(zeros, Uf), 1.0*CFL)

# mask positives, keep negatives
CFL_masked.mask = np.logical_not(CFL_masked.mask)
zeros.mask = CFL_masked.mask
#operating only on negative values
CFL_final_neg = ma.minimum(ma.maximum(-1.0*CFL_masked, Uf), zeros)

CFL_final = np.zeros_like(CFL)

CFL_final = np.where(CFL_final_neg.mask == False, CFL_final_neg.data, CFL_final_pos.data)

1 loops, best of 3: 327 ms per loop


In [5]:
%%timeit 
Uf_limited = np.zeros_like(CFL)
for j in range(CFL.shape[1]):
    for i in range(CFL.shape[0]):
        if CFL[i,j] >= 0:
            Uf_limited[i,j] = min( [ max([0,Uf[i,j]]), 1.0*CFL[i,j]] )
        else: # U < 0
            Uf_limited[i,j] = min( [ max([-1.0*CFL[i,j], Uf[i,j]]), 0 ] )

1 loops, best of 3: 4.1 s per loop


In [107]:
.340*1536/60

8.704

[[-0.42273195  0.08891318 -0.30134986 -0.41019624  0.21007889]
 [-0.68022488  0.64590769  0.30939136  0.94322453 -0.72466147]
 [ 0.87766269 -1.46644229  0.50089301  0.22964166  0.66403735]
 [ 0.87328908 -0.85639999  0.1983523  -0.32506426 -0.36472375]
 [-0.9361809   0.12797658 -0.10994567 -0.39484037  1.1583446 ]]


In [62]:
a = np.array([2,-4,5,6,-7,3,3])

np.minimum(np.zeros_like(a), a)

array([ 0, -4,  0,  0, -7,  0,  0])

In [12]:
import numpy as np
import numpy.ma as ma

Uf = np.random.randn(768,1536)
f_old = np.random.randn(768,1536)
CFLfrac = np.random.randn(768, 1536)

Uf_looped = np.zeros_like(Uf)
Uf_masked = np.zeros_like(Uf)

In [19]:
%%timeit

# local masked array (ma) copy of CFL.frac used to leave CFL.frac unchanged
Uf_ma = ma.array(CFLfrac)

# mask negative values, keep positives
Uf_ma[CFLfrac < 0] = ma.masked

# assign the mask to a zero matrix of same size for pairwise ma.minimum/maximum operations below
zeros = ma.zeros(Uf_ma.shape)
zeros.mask = Uf_ma.mask

# operating only on positive values
Uf_pos = ma.minimum(ma.maximum(zeros, Uf), 1.0*f_old)

# mask positives, keep negatives
Uf_ma.mask = np.logical_not(Uf_ma.mask)
zeros.mask = Uf_ma.mask

#operating only on negative values
Uf_neg = ma.minimum(ma.maximum(-1.0*f_old, Uf), zeros)

# combine masked values in a single matrix Uf_final
Uf_masked = np.where(Uf_neg.mask == False, Uf_neg.data, Uf_pos.data)

1 loops, best of 3: 285 ms per loop


In [18]:
%%timeit

for i in range(768):
    for j in range(1536):
        if CFLfrac[i,j] >= 0:
            Uf_looped[i,j] = min( [ max([0,Uf[i,j]]), 1.0*f_old[i,j]] )
        else: # U < 0
            Uf_looped[i,j] = min( [ max([-1.0*f_old[i,j], Uf[i,j]]), 0 ] )


1 loops, best of 3: 3.85 s per loop


In [15]:
print Uf_masked

[[-0.88553308  0.         -1.0370018  ..., -2.7049262   0.71222341  0.        ]
 [ 0.         -0.46244508  0.         ...,  0.         -0.76610589
  -1.01759015]
 [ 0.          0.          0.         ...,  0.30927549 -0.62269486
  -1.38868009]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.         -1.89634589]
 [-1.01152627  0.51994309  0.         ..., -1.55360964  0.         -0.38993789]
 [ 0.          0.         -0.96108724 ...,  0.          0.          0.        ]]


In [17]:
print Uf_looped == Uf_masked

[[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]]


In [20]:
print Uf_masked

[[-0.88553308  0.         -1.0370018  ..., -2.7049262   0.71222341  0.        ]
 [ 0.         -0.46244508  0.         ...,  0.         -0.76610589
  -1.01759015]
 [ 0.          0.          0.         ...,  0.30927549 -0.62269486
  -1.38868009]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.         -1.89634589]
 [-1.01152627  0.51994309  0.         ..., -1.55360964  0.         -0.38993789]
 [ 0.          0.         -0.96108724 ...,  0.          0.          0.        ]]


In [21]:
print Uf_looped

[[-0.88553308  0.         -1.0370018  ..., -2.7049262   0.71222341  0.        ]
 [ 0.         -0.46244508  0.         ...,  0.         -0.76610589
  -1.01759015]
 [ 0.          0.          0.         ...,  0.30927549 -0.62269486
  -1.38868009]
 ..., 
 [ 0.          0.          0.         ...,  0.          0.         -1.89634589]
 [-1.01152627  0.51994309  0.         ..., -1.55360964  0.         -0.38993789]
 [ 0.          0.         -0.96108724 ...,  0.          0.          0.        ]]


In [22]:
print Uf # before reusing the same for different assignment

[[-2.16224416 -1.52292136 -1.21732665 ...,  0.73707302  1.0666574
   0.27822448]
 [-0.17025956  0.64556053 -2.04819017 ...,  1.06146852 -0.76610589
  -1.01759015]
 [ 0.45099407 -1.06445293  0.53029705 ...,  0.30927549  0.40730623
  -1.57517373]
 ..., 
 [-1.05049694  0.23746652 -0.00552269 ..., -1.16439685 -0.99899952
   1.11465052]
 [ 0.00483184  0.51994309 -0.39519637 ..., -0.8617551   0.621127   -0.2432048 ]
 [-0.18432247 -1.64188282  0.78446744 ..., -0.7719988   0.65521122
   0.40078797]]


In [23]:
# local masked array (ma) copy of CFL.frac used to leave CFL.frac unchanged
Uf_ma = ma.array(CFLfrac)

# mask negative values, keep positives
Uf_ma[CFLfrac < 0] = ma.masked

# assign the mask to a zero matrix of same size for pairwise ma.minimum/maximum operations below
zeros = ma.zeros(Uf_ma.shape)
zeros.mask = Uf_ma.mask

# operating only on positive values
Uf_pos = ma.minimum(ma.maximum(zeros, Uf), 1.0*f_old)

# mask positives, keep negatives
Uf_ma.mask = np.logical_not(Uf_ma.mask)
zeros.mask = Uf_ma.mask

#operating only on negative values
Uf_neg = ma.minimum(ma.maximum(-1.0*f_old, Uf), zeros)

# combine masked values in a single matrix Uf_final
Uf = np.where(Uf_neg.mask == False, Uf_neg.data, Uf_pos.data)

In [25]:
print Uf == Uf_masked

[[ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 ..., 
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]
 [ True  True  True ...,  True  True  True]]
